// Recovered, readable pseudocode for dac-1.20.dll.
// This is not original source. It is a static reconstruction from:
// - JNI exports in dlls/dac-1.20.dll
// - Java call sites in src-decompiled/org/ywzj/doganticheat
// - import table and string analysis
//
// The DLL was not loaded or executed while producing this file.

#include <cstdint>
#include <string>
#include <unordered_set>
#include <vector>

using bytes = std::vector<std::uint8_t>;

struct NativeState {
    bytes rsa_public_key_der;
    bool enabled = false;
};

static NativeState g_state;

// JNI: NativeApi.core0()
// Java: started from Premain before normal mod initialization.
//
// Recovered role:
//   Starts the native engine/background monitor. Import table and strings show
//   access to process enumeration, memory APIs, window/screenshot APIs, TPM,
//   registry, debugger checks, and VM/sandbox checks.
void NativeApi_core0_pseudocode() {
    // likely:
    //   initialize native runtime
    //   install anti-debug/exception handlers
    //   collect host/process/window/hardware state
    //   keep a monitor loop alive
}

// JNI: NativeApi.op2(byte[] publicKeyDer)
// Java: Premain passes an X.509 RSA public key.
void NativeApi_op2_pseudocode(const bytes& publicKeyDer) {
    g_state.rsa_public_key_der = publicKeyDer;
}

// JNI: NativeApi.op3(byte flag)
// Java: Premain calls op3(1) after op2.
void NativeApi_op3_pseudocode(std::uint8_t flag) {
    g_state.enabled = (flag != 0);
}

// JNI: NativeApi.op0()
// Java: JoinMultiplayerScreenMixin sends Base64(op0()) as JSON field "data".
bytes NativeApi_op0_pseudocode() {
    // likely:
    //   serialize native environment / anti-cheat attestation payload
    //   include process, hardware, debugger, VM, or integrity results
    return bytes{/* opaque native payload */};
}

// JNI: NativeApi.op1(int, float, float, float, float)
// Java: movement/combat-related packet helper from obfuscated packet code.
bytes NativeApi_op1_pseudocode(int code, float a, float b, float c, float d) {
    // likely:
    //   pack or sign client telemetry values
    return bytes{/* opaque packet payload */};
}

// JNI: NativeApi.core1(byte[])
// Java bridge name c.a(byte[]).
bytes NativeApi_core1_pseudocode(const bytes& input) {
    // likely generic native transform.
    return bytes{/* transformed input */};
}

// JNI: NativeApi.op4(byte[])
// Java bridge name c.c(byte[]).
bytes NativeApi_op4_pseudocode(const bytes& input) {
    // likely packet/config transform.
    return bytes{/* transformed input */};
}

// JNI: NativeApi.op5(byte[])
// Java bridge name c.d(byte[]).
//
// Confirmed Java uses:
//   - decrypt config key "w" into a gateway URL
//   - decrypt config key "f" into the real server address
//   - decrypt encrypted jar bytes in EncryptedFileSystem fallback
//
// Static notes:
//   - Export RVA: 0x1cd460.
//   - Function begins with JNI GetArrayLength/GetByteArrayElements-style byte[]
//     plumbing, copies input to native scratch buffers, then calls internal
//     obfuscated helpers.
//   - The default w/f ciphertexts are AES-block-sized, not raw RSA blocks.
//   - The DLL imports OpenSSL EVP AES-128-ECB and RSA public operations, but
//     direct crypto calls are hidden behind indirect calls or helper tables.
bytes NativeApi_op5_pseudocode(const bytes& encrypted) {
    // observed high-level behavior:
    //
    // bytes native_input = copy_from_jbyteArray(encrypted);
    // bytes decrypted = internal_decrypt_or_vm_transform(native_input);
    // return new_jbyteArray(decrypted);
    //
    // Expected plaintext for JoinMultiplayerScreenMixin:
    //   op5(Base64.decode(config["w"])) -> UTF-8 gateway URL
    //   op5(Base64.decode(config["f"])) -> UTF-8 real server address
    return bytes{/* decrypted bytes */};
}

// JNI: NativeApi.op6(java.util.List)
// Java: resource/shader/TACZ scan result encoder.
bytes NativeApi_op6_pseudocode(/* java.util.List */) {
    // likely:
    //   serialize scan list
    //   encrypt/sign it for server report
    return bytes{/* encoded report */};
}

// JNI: NativeApi.op7()
bytes NativeApi_op7_pseudocode() {
    return bytes{/* native generated bytes */};
}

// JNI: NativeApi.op8(byte[])
bytes NativeApi_op8_pseudocode(const bytes& input) {
    return bytes{/* transformed input */};
}

// JNI: NativeApi.op9(int, byte[])
bytes NativeApi_op9_pseudocode(int code, const bytes& input) {
    return bytes{/* transformed input */};
}

// JNI: NativeApi.op10()
// Java bridge returns HashSet.
std::unordered_set<std::string> NativeApi_op10_pseudocode() {
    // likely:
    //   return detected process/window/debugger/VM/environment flags
    return {};
}

// JNI: NativeApi.test()
void* NativeApi_test_pseudocode() {
    return nullptr;
}
